{{-- admin/reports.blade.php --}}
@extends('layouts.app')
@section('title', 'Reports')

@section('content')
<h4 class="fw-bold mb-4"><i class="bi bi-bar-chart me-2 text-primary"></i>Reports</h4>

<div class="card">
    <div class="card-body p-0">
        <table class="table table-hover mb-0">
            <thead><tr><th>Title</th><th>Type</th><th>Generated By</th><th>Date</th><th>Format</th></tr></thead>
            <tbody>
            @forelse($reports as $r)
                <tr>
                    <td>{{ $r->title }}</td>
                    <td><span class="badge bg-secondary">{{ $r->type }}</span></td>
                    <td>{{ $r->admin->user->fullName ?? '—' }}</td>
                    <td>{{ $r->generatedAt->format('d M Y H:i') }}</td>
                    <td>{{ $r->format }}</td>
                </tr>
            @empty
                <tr><td colspan="5" class="text-center py-4 text-muted">No reports generated yet.</td></tr>
            @endforelse
            </tbody>
        </table>
    </div>
    @if($reports->hasPages())
        <div class="card-footer bg-white">{{ $reports->links() }}</div>
    @endif
</div>
@endsection
